version: 2.1
jobs:
  build:
    docker:
      - image: google/cloud-sdk:emulators
      - image: google/cloud-sdk:emulators
      - image: localstack/localstack
      - image: cimg/redis:6.0
    steps:
      - checkout
      - run: echo "hello wowwaaa"
